<a href="https://colab.research.google.com/github/sangeeth-sathyan-k/DSproject/blob/master/Diabetes_prediction_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv('/content/drive/MyDrive/AICTE Project/diabetes_prediction_dataset.csv')

In [32]:
df.head()

gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [33]:
df.shape

(100000, 9)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   gender               100000 non-null  object 
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64  
 3   heart_disease        100000 non-null  int64  
 4   smoking_history      100000 non-null  object 
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64  
 8   diabetes             100000 non-null  int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB


In [35]:
df.isna().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [36]:
for i in df.columns:
  print(df[i].unique(),i)
  print('_______________________________')

['Female' 'Male' 'Other'] gender
_______________________________
[80.   54.   28.   36.   76.   20.   44.   79.   42.   32.   53.   78.
 67.   15.   37.   40.    5.   69.   72.    4.   30.   45.   43.   50.
 41.   26.   34.   73.   77.   66.   29.   60.   38.    3.   57.   74.
 19.   46.   21.   59.   27.   13.   56.    2.    7.   11.    6.   55.
  9.   62.   47.   12.   68.   75.   22.   58.   18.   24.   17.   25.
  0.08 33.   16.   61.   31.    8.   49.   39.   65.   14.   70.    0.56
 48.   51.   71.    0.88 64.   63.   52.    0.16 10.   35.   23.    0.64
  1.16  1.64  0.72  1.88  1.32  0.8   1.24  1.    1.8   0.48  1.56  1.08
  0.24  1.4   0.4   0.32  1.72  1.48] age
_______________________________
[0 1] hypertension
_______________________________
[1 0] heart_disease
_______________________________
['never' 'No Info' 'current' 'former' 'ever' 'not current'] smoking_history
_______________________________
[25.19 27.32 23.45 ... 59.42 44.39 60.52] bmi
______________________________

In [37]:
for i in df.columns:
  print(df[i].value_counts())
  print('________________________________')

gender
Female    58552
Male      41430
Other        18
Name: count, dtype: int64
________________________________
age
80.00    5621
51.00    1619
47.00    1574
48.00    1568
53.00    1542
         ... 
0.48       83
1.00       83
0.40       66
0.16       59
0.08       36
Name: count, Length: 102, dtype: int64
________________________________
hypertension
0    92515
1     7485
Name: count, dtype: int64
________________________________
heart_disease
0    96058
1     3942
Name: count, dtype: int64
________________________________
smoking_history
No Info        35816
never          35095
former          9352
current         9286
not current     6447
ever            4004
Name: count, dtype: int64
________________________________
bmi
27.32    25495
23.00      103
27.12      101
27.80      100
24.96      100
         ...  
56.10        1
50.27        1
55.04        1
56.65        1
53.37        1
Name: count, Length: 4247, dtype: int64
________________________________
HbA1c_level
6.6    8540


In [38]:
dup = df.duplicated().sum()
dup

np.int64(3854)

In [39]:
df = df.drop_duplicates()

In [40]:
df.shape

(96146, 9)

In [41]:
df.describe()

age  hypertension  heart_disease           bmi   HbA1c_level  \
count  96146.000000  96146.000000   96146.000000  96146.000000  96146.000000   
mean      41.794326      0.077601       0.040803     27.321461      5.532609   
std       22.462948      0.267544       0.197833      6.767716      1.073232   
min        0.080000      0.000000       0.000000     10.010000      3.500000   
25%       24.000000      0.000000       0.000000     23.400000      4.800000   
50%       43.000000      0.000000       0.000000     27.320000      5.800000   
75%       59.000000      0.000000       0.000000     29.860000      6.200000   
max       80.000000      1.000000       1.000000     95.690000      9.000000   

       blood_glucose_level      diabetes  
count         96146.000000  96146.000000  
mean            138.218231      0.088220  
std              40.909771      0.283616  
min              80.000000      0.000000  
25%             100.000000      0.000000  
50%             140.000000      0.000000  
75%             159.000000      0.000000  
max             300.000000      1.000000

In [42]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['gender'] = le.fit_transform(df['gender'])
df['smoking_history'] = le.fit_transform(df['smoking_history'])

In [43]:
df

gender   age  hypertension  heart_disease  smoking_history    bmi  \
0           0  80.0             0              1                4  25.19   
1           0  54.0             0              0                0  27.32   
2           1  28.0             0              0                4  27.32   
3           0  36.0             0              0                1  23.45   
4           1  76.0             1              1                1  20.14   
...       ...   ...           ...            ...              ...    ...   
99994       0  36.0             0              0                0  24.60   
99996       0   2.0             0              0                0  17.37   
99997       1  66.0             0              0                3  27.83   
99998       0  24.0             0              0                4  35.42   
99999       0  57.0             0              0                1  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99994          4.8                  145         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[96146 rows x 9 columns]

In [44]:
corln = df.corr()['diabetes']
corln

gender                 0.037613
age                    0.264927
hypertension           0.195710
heart_disease          0.170711
smoking_history        0.088471
bmi                    0.214932
HbA1c_level            0.406408
blood_glucose_level    0.424336
diabetes               1.000000
Name: diabetes, dtype: float64

In [45]:
x = df.iloc[:,:-1]
x

gender   age  hypertension  heart_disease  smoking_history    bmi  \
0           0  80.0             0              1                4  25.19   
1           0  54.0             0              0                0  27.32   
2           1  28.0             0              0                4  27.32   
3           0  36.0             0              0                1  23.45   
4           1  76.0             1              1                1  20.14   
...       ...   ...           ...            ...              ...    ...   
99994       0  36.0             0              0                0  24.60   
99996       0   2.0             0              0                0  17.37   
99997       1  66.0             0              0                3  27.83   
99998       0  24.0             0              0                4  35.42   
99999       0  57.0             0              0                1  22.43   

       HbA1c_level  blood_glucose_level  
0              6.6                  140  
1              6.6                   80  
2              5.7                  158  
3              5.0                  155  
4              4.8                  155  
...            ...                  ...  
99994          4.8                  145  
99996          6.5                  100  
99997          5.7                  155  
99998          4.0                  100  
99999          6.6                   90  

[96146 rows x 8 columns]

In [46]:
y = df['diabetes']
y

0        0
1        0
2        0
3        0
4        0
        ..
99994    0
99996    0
99997    0
99998    0
99999    0
Name: diabetes, Length: 96146, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [48]:
ytrain.value_counts()

diabetes
0    70102
1     6814
Name: count, dtype: int64

In [49]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(xtrain)
xtrain = scaler.transform(xtrain)

scaler.fit(xtest)
xtest = scaler.transform(xtest)

In [50]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 3,weights = 'distance',p = 2)

knn.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [51]:
ypred = knn.predict(xtest)
ypred

array([0, 1, 0, ..., 0, 0, 0])

In [52]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

accuracy_score(ytest,ypred)

0.9551742069682787

In [53]:
print(confusion_matrix(ytest,ypred))

[[17272   290]
 [  572  1096]]


In [54]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98     17562
           1       0.79      0.66      0.72      1668

    accuracy                           0.96     19230
   macro avg       0.88      0.82      0.85     19230
weighted avg       0.95      0.96      0.95     19230



In [55]:

input_data = (0,80,0,1,4,25.19,6.6,140)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = knn.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[[0.         1.         0.         1.         0.8        0.1774724
  0.56363636 0.27272727]]
[0]
The person is not diabetic


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
